### ISSUE TITLE
🔥 🔥 🔥 Nice to see someone working with EmberJS! 🔥 🔥 🔥 

### ISSUE THREAD

**Issue by robert-hoekstra** [CountNick/frontend-applications#10]
It is great to see that you kept on going with Ember. A lot of people nowadays quit EmberJS because they give up easily. But you did not do that. Thanks for the in real life help!

🍐 🐾 🔙  for you!

**Comment by CountNick** [comment]
Hahaha yes for sure not one of the best documented frameworks to be found:clown_face: Happy that to help:sos:
